name: RaiseAmountOfChestItems
main: com.github.smk7758.RaiseAmountOfChestItems.Main
version: 0.0.1
author: smk7758
permissions:
commands:
  RaiseAmountOfChestItems:
    description: RaiseAmountOfChestItems's command.
    aliases: [raise, raoci]